### ISSUE TITLE
Add splunk as a datasource

### ISSUE THREAD

**Issue by MadaraUchiha-314** [intuit/fawkes#10]
## 🚀 Feature Proposal

A lot of user reviews may go into splunk. Splunk exposes an API which can directly be used to achieve this.

## Motivation

To track those user reviews which go into splunk.

## Example

Splunk can now become a data source.

**Comment by smandalika1** [comment]
@MadaraUchiha-314 - Is this still needed?

**Comment by MadaraUchiha-314** [comment]
@smandalika1 Yes.

**Comment by kokikathir** [comment]
@MadaraUchiha-314, I m interested in this

**Comment by MadaraUchiha-314** [comment]
@kokikathir Sure Feel free to take it up.

**Comment by kokikathir** [comment]
Thanks @MadaraUchiha-314

Can you give me some overview of the task

**Comment by kokikathir** [comment]
@MadaraUchiha-314, I m planning to use the below config for splunk. Is it fine?

`{
            "channel_type": "splunk",
            "channel_name": "pi",
            "file_type": "json",
            "file_path": null,
            "is_channel_enabled": true,
            "timestamp_key": "updated",
            "timestamp_format": "",
            "timezone": "UTC",
            "message_key": "content",
            "rating_key": "rating",
            "host": "splunk-rest-***",
            "port": 443,
            "username": "***",
            "password": "***",
            "query" : "index=**",
            "earliest_time" : "15m",
            "latest_time" : "now"
        }`
