### ISSUE TITLE
Auto clustering of user reviews

### ISSUE THREAD

**Issue by MadaraUchiha-314** [intuit/fawkes#16]
Currently fawkes only has classification for user reviews, which requires either static weights if we are using text-match or already labelled data to use the LSTM based classification model.

It would be nice to have an automatic clustering of user reviews to get an initial sense of all the topics within the data set.

The important thing is to have a model which can be saved and reused in the future for further clustering when new user reviews are added to the dataset.

**Comment by rohit256** [comment]
I'm interested !

**Comment by MadaraUchiha-314** [comment]
@rohit256 Kindly come up with a plan on what algorithms you are planning to contribute.

**Comment by mbrine555** [comment]
I'd be interested in working on this if you're still looking for somebody. My thought is to just get something pretty simple like LDA up and running, and then maybe fiddle around to see if there's anything more sophisticated that might work better.

**Comment by ayonya100** [comment]
Please assign this to me! Thanks!

**Comment by MadaraUchiha-314** [comment]
@mbrine555 We had tied to run LDA on this. Results were not good. Although I think we had not tuned it well enough. Give it a try and let us know what happens.

**Comment by mbrine555** [comment]
@MadaraUchiha-314 Sounds good! I'll keep you in the loop on what I come up with.
