### ISSUE TITLE
Summarisation of user reviews

### ISSUE THREAD

**Issue by MadaraUchiha-314** [intuit/fawkes#17]
Going though a lot of user reviews takes time. Having a summary view of all the issues would be a great feature to have.

**Comment by rohit256** [comment]
I'm interested in working on this issue!

**Comment by MadaraUchiha-314** [comment]
Assgined.

**Comment by prajwalppv** [comment]
@MadaraUchiha-314 Interested in working on this issue as well! 
Will take a stab at it. :)
