### ISSUE TITLE
Add App Config schema validation

### ISSUE THREAD

**Issue by MadaraUchiha-314** [intuit/fawkes#19]
Currently the App. Config. [app/sample-mint-config.json] is converted directly to a class object. Need to add a schema validation using JSON schema for it to be more robust and catch errors before running the code.

[app/sample-mint-config.json]: https://github.com/intuit/fawkes/blob/master/app/sample-mint-config.json

**Comment by kokikathir** [comment]
@MadaraUchiha-314 I would like to pick this

**Comment by aditi2205** [comment]
@MadaraUchiha-314 I would like to work on this

**Comment by kokikathir** [comment]
@MadaraUchiha-314 the schema should be based on certain required fields, right? 
For example, In the case of review channels, spreadsheet_id and sheet_id should be validated, when the channel_type is spreadsheet. 

Is my assumption correct?

**Comment by MadaraUchiha-314** [comment]
@aditi2205 Can you pick up any other issue ? @kokikathir told me that the work has already been started on this issue.

**Comment by aditi2205** [comment]
Sure
