### ISSUE TITLE
Add the capability to fetch data from Elasticsearch api

### ISSUE THREAD

**Issue by Konoha-14** [intuit/fawkes#20]
Given any search query, add the support to fetch data and save it in specified format (json, csv)

Resource: https://www.elastic.co/guide/en/elasticsearch/reference/current/rest-apis.html

**Comment by nprajilesh** [comment]
@Konoha-14 i will take this one. could you assign this to me?

**Comment by kokikathir** [comment]
@Konoha-14 I would like to take this up

**Comment by aditi2205** [comment]
@Konoha-14 Can I take it up as @kokikathir is working on #19 as well

**Comment by kokikathir** [comment]
@aditi2205 I m not working on this. You can proceed

**Comment by MadaraUchiha-314** [comment]
@aditi2205 Assigned it to you.

**Comment by aditi2205** [comment]
@MadaraUchiha-314 @Konoha-14 
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-search.html
Documentation refers to two types of GET requests in search API, which one should be added? I was thinking of putting in an optional target URL parameter, that will support both the endpoints
